### ISSUE TITLE
[Bug] outdated angular-cli-ghpages version for nx projects

### ISSUE THREAD

**Issue by geromegrignon** [ngneat/lib#35]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

By running `ng add @ngneat/lib <lib-name>` in a Nx project, the schematic fails on `ng add angular-cli-ghpages` part.

```bash
SchematicsException [Error]: No Angular project selected and no default project in the workspace
    at /Users/geromegrignon/Documents/workspace/oneshots/foo/node_modules/angular-cli-ghpages/ng-add.js:25:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/geromegrignon/Documents/workspace/oneshots/foo/node_modules/angular-cli-ghpages/ng-add.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

## Expected behavior

The schematic should find the `defaultProject` info.

It's due to the `angular-cli-ghpages` version used.
Changes occurred in the lib with this [commit](https://github.com/angular-schule/angular-cli-ghpages/pull/139).

`ng add angular-cli-ghpages` with latest version (v1.0.0) in a nx project works as expected

## Minimal reproduction of the problem with instructions

create a nx workspace with `npx create-nx-workspace --preset=angular`.
run `ng add @ngneat/lib <lib-name>`

## Changes required

Change `angular-cli-ghpages` version used in the schematic to `v1.0.0`.

## Others:

Once accepted as a valid change, I will communicate to encourage people to submit a PR to fix it.

**Comment by shhdharmen** [comment]
Sound good.
